version: '3'

services:
  db:
    image: postgres

    container_name: event-database

    restart: always

    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: event-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass123
